### ISSUE TITLE
Use with Android Studio and Java

### ISSUE THREAD

**Issue by MalusDarkb** [Ramotion/fluid-slider-android#10]
Is it possible to use the code in a Java class? 
I could not implement a PositionListener. 
I tried to use it with a onTouchListener but the setPosition() Method does not work once I use the onTouchListener(). Is there another workaround or way to implement this? I have never tried to embed kotlin code into Java. 

Thanks!

**Comment by dvg4000** [comment]
https://github.com/Ramotion/fluid-slider-android/issues/5#issuecomment-365164832
