### ISSUE TITLE
Touch event

### ISSUE THREAD

**Issue by gcalaprice** [Ramotion/fluid-slider-android#13]
Hi, there's a way to delay the bubble rise? I have a recyclerview with a fluidslider per element and when I scroll down the list the slider instantly intercept the event and start the tracking listener. I want to set a delay (something like click and hold pattern) to the bubble. Let me know is there's already the way or if I have to implement it on my own. Thanks.

**Comment by dvg4000** [comment]
There is no way to 'delay the bubble rise'.
