### ISSUE TITLE
Caculations in drawMetaball 

### ISSUE THREAD

**Issue by ltvu93** [Ramotion/fluid-slider-android#16]
Hello, I want use code in drawMetaball method for custom my widgets, but the caculations is too hard. Can you provide me some clues or geometric drawing? Thank you.

**Comment by golovin47** [comment]
Hello, ltvu93. The code itself is pretty much self documented. The best way to understand it to use in your project is by passing your own parameters to drawMetaball method, i.e. 
canvas: Canvas, paint: Paint, path: Path, circle1: RectF, circle2: RectF, topBorder: Float, 
riseDistance: Float, maxDistance: Float, cornerRadius: Float, topSpreadFactor: Float, bottomStartSpreadFactor: Float, bottomEndSpreadFactor: Float, handleRate: Float

You will see how it behaves, so it will be easier to understand the logic of it.
