### ISSUE TITLE
Re-setting position

### ISSUE THREAD

**Issue by vanpana** [Ramotion/fluid-slider-android#17]
When I init my activity, I set the position and it successfully works.

But the second time I try to set the position, the value is set, but the bubble is still in the old position.

How can I fix that?

**Comment by dvg4000** [comment]
You need to call `slider.invalidate()` after setting position. I will change this behavior in next version or add new method that will update FluidSlider visual position immediately.

**Comment by vanpana** [comment]
I've managed to do it with invalidate, but I thought it would've been a better way. Thanks for the help.
