### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Ramotion/fluid-slider-android#21]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Juriv** [comment]
@mansya sure, go ahead 👍

**Comment by mansya** [comment]
I have desing logo for this project. what do you think ? which one do you like it ? 
![fluid slider android](https://user-images.githubusercontent.com/33461607/44947129-9c60fd80-ae32-11e8-89c7-0f072ac97974.png)

the blue wave depicts a liquid that is wavy. and the line below describes the slide. I designed it as if it were fluid running on the slide below it. this is a design according to the project name and how the application works.

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.
