### ISSUE TITLE
How to slide automatically as the progress updates in Java?

### ISSUE THREAD

**Issue by coolamz** [Ramotion/fluid-slider-android#24]

**Comment by golovin47** [comment]
Hello, @coolamz. Right now there is only one way to update slider progress - apply touch events. So you can reach such behavior by dispatching a touch event on a slider programmatically.
Example:

val downTime = SystemClock.uptimeMillis()
val eventTime = SystemClock.uptimeMillis() + 100
val x = 0.0f
val y = 0.0f
int metaState = 0
val motionEvent = MotionEvent.obtain(
    downTime, 
    eventTime, 
    MotionEvent.ACTION_MOVE, 
    x, 
    y, 
    metaState
)

slider.dispatchTouchEvent(motionEvent)
