### ISSUE TITLE
how can i get the bubble value

### ISSUE THREAD

**Issue by mima5** [Ramotion/fluid-slider-android#26]
Hello
Am fresh at java 
can you please tell me how i get the value of the bubble 
how can i store  the value ?

**Comment by dazfx** [comment]
import kotlin.Unit;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.functions.Function1;

    private float _initialPosition;
    private float _position;

slider.setPositionListener(new Function1<Float, Unit>() {
            @Override
            public Unit invoke(Float pos) {
                _position = pos;
                tw2 = (TextView) findViewById(R.id.textView2);
                tw2.setText(String.valueOf((int) (min + ((max - min) * _position))));
                return Unit.INSTANCE;
            }
        });
