### ISSUE TITLE
IllegalArgumentException, wrong state class

### ISSUE THREAD

**Issue by mayurolls** [Ramotion/fluid-slider-android#27]
### while coming back to this fragment.. it is giving the following error on backpress method
 java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.ramotion.fluidslider.FluidSlider$State instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/fluid_Slider. Make sure other views do not use the same id.

I have followed the code from this example..

**Comment by golovin47** [comment]
Hello, @mayurolls. This issue was resolved by @payasgupta's commit.
