### ISSUE TITLE
direction rtl

### ISSUE THREAD

**Issue by freehussain** [Ramotion/fluid-slider-android#31]
hello,

i want to use this for direction rtl, can you help me please?

kind regards

**Comment by golovin47** [comment]
Hello, @freehussain. You can use it with rtl. Steps to apply:
1. Use your startText as endText and your endText as startText in fluidSlider. 
2. Use inverted position in positionListener callback function.

Example:

val max = 45
val min = 10
val total = max - min

val slider = findViewById<FluidSlider>(R.id.fluidSlider)
slider.positionListener = { pos -> val invertedPosition = 1f - pos; slider.bubbleText = "${min + (total  * invertedPosition).toInt()}" }
slider.position = 0.7f
slider.startText ="$max"
slider.endText = "$min"

This is the simplest way to use fluidSlider with rtl (invertion of values). Other way is changing the source code inside the library.
