### ISSUE TITLE
How to set custom font for bar and bubble ?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [Ramotion/fluid-slider-android#35]
First of all i must thanks you for the fantastic library  Now my primary doubt is how to set custom font for bar and bubble text ? is there any workaround to add

**Comment by golovin47** [comment]
Hello, @YogeshLegendkiller. There is no such feature in this lib. But if you need to change font, you're welcome to fork this lib and change it the way you need in FluidSlider.kt.
