### ISSUE TITLE
Increment by X value

### ISSUE THREAD

**Issue by codeversed** [Ramotion/fluid-slider-android#39]
I am looking to add a way to use increments of 10. So if I had max set to 100, it would jump 10, 20, 30... 80, 90, 100 and allow no other values. Is there any way to currently do this or an easy way to add this functionality?

For Kotlin, I would guess we would need to modify the ACTION_MOVE event?

**Comment by golovin47** [comment]
Hello, @codeversed. You are right, you may change ACTION_MOVE event to achieve behavior you need. Also this may help you https://docs.oracle.com/javase/6/docs/api/java/text/NumberFormat.html.
