### ISSUE TITLE
Floating point 

### ISSUE THREAD

**Issue by p-gentili** [Ramotion/fluid-slider-android#4]
It would be interesting to have floating point range with the possibility to tweak the number of decimal places.

**Comment by dvg4000** [comment]
I do not quite understand what you mean. Can you please describe more clearly.

**Comment by p-gentili** [comment]
I'd like to have a range from 1.0 to 30.0 with a step of 0.1. Is it possibile?

**Comment by dvg4000** [comment]
`FluidSlide.position` changes from `0.0f` to `1.0f`. Here is shown how to change range and `bubbleText`: https://github.com/Ramotion/fluid-slider-android/issues/2#issuecomment-364995790

**Comment by p-gentili** [comment]
Thanks!
