### ISSUE TITLE
FluidSlider disable help wanted.

### ISSUE THREAD

**Issue by sanjaypatel27** [Ramotion/fluid-slider-android#40]
hello 
 I want to disable the FluidSlider in some condition.
 I want to stop the user to slide the FluidSlider in some case and in another case they can use the  FluidSlider to change value.
I tried to use disable and clickable but it's not working. 
can you please help me with this.

**Comment by golovin47** [comment]
Hello, @sanjaypatel27. To disable any interaction with slider you need to set your own touch listener to it. You can do it this way:
```
slider.setOnTouchListener { view, motionEvent ->
            return@setOnTouchListener true
        }
```
Returning true will disable it. To enable it you need to set touch listener again, but it should return false. You can do it this way:
```
slider.setOnTouchListener { view, motionEvent ->
            return@setOnTouchListener false
        }
```

**Comment by sanjaypatel27** [comment]
Thank you so much @golovin47.
