### ISSUE TITLE
Can't install the package when use it in Fragement 

### ISSUE THREAD

**Issue by zgao67** [Ramotion/fluid-slider-android#43]
Installed the package in Gradle 
tried to use it in Fragement 

`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view =  inflater.inflate(R.layout.fragment1, container, false);

        final int max = 10;
        final int min = 0;
        final int total = max - min;

        final FluidSlider slider = view.findViewById(R.id.fluidSlider);

        slider.setBeginTrackingListener(new Function0<Unit>() {
            @Override
            public Unit invoke() {
                Log.d("D", "setBeginTrackingListener");
                return Unit.INSTANCE;
            }
        });

        slider.setEndTrackingListener(new Function0<Unit>() {
            @Override
            public Unit invoke() {
                Log.d("D", "setEndTrackingListener");
                return Unit.INSTANCE;
            }
        });

        slider.setPositionListener(pos -> {
            final String value = String.valueOf( (int)((1 - pos) * 100) );
            slider.setBubbleText(value);
            return Unit.INSTANCE;
        });

        slider.setPosition(0.3f);
        slider.setStartText(String.valueOf(min));
        slider.setEndText(String.valueOf(max));

        // Inflate the layout for this fragment
        return view;
    }

`

I had to manually install it in the XML like this: 

```
> 
>     <com.ramotion.fluidslider.FluidSlider
>         android:id="@+id/fluidSlider"
>         android:layout_width="376dp"
>         android:layout_height="58dp"
>         android:layout_marginStart="16dp"
>         android:layout_marginTop="32dp"
>         android:layout_marginEnd="16dp"
>         android:background="#5C6BC0"
>         android:elevation="2dp"
>         app:duration="@android:integer/config_mediumAnimTime"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintHorizontal_bias="1.0"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toBottomOf="@+id/textView6"
>         app:size="small"
>         tools:targetApi="lollipop" />
```
As i can't find the package in the design - palette 
Please hlep

**Comment by golovin47** [comment]
Hello @zgao67. It is absolutely doesn't matter where to use it in activity or in fragment. Check how it is done in the example app in this repo.
