### ISSUE TITLE
How to get Bubble value on setEndTrackingListener?

### ISSUE THREAD

**Issue by harshad008** [Ramotion/fluid-slider-android#7]
Hello,
I am using it with java class,I want to get Bubble text value on end tracking.How to get it..?

` fluidSlider.setEndTrackingListener(() -> { 
return Unit.INSTANCE;
}); `

**Comment by dvg4000** [comment]
Hello. Here is how:
```java
fluidSlider.setEndTrackingListener(() -> { 
    final String text = String.valueOf((int)(fluidSlider.getPosition() * 100));
    return Unit.INSTANCE; 
});
```

**Comment by harshad008** [comment]
@dvg4000 Thanx. its working.
